In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import warnings
warnings.filterwarnings('ignore')
import os

In [2]:
os.getcwd()

'C:\\Users\\Itvedant CR4-4\\Downloads'

In [3]:
df=pd.read_csv("creditcard.csv")
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [5]:
x=df[["Time","Amount"]]
y=df["Class"]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,
                                              random_state=1)

In [7]:
from sklearn.preprocessing import StandardScaler
#create object of StandardScaler class
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

In [8]:
x_train.shape

(199364, 2)

In [9]:
y_train.value_counts()

0    199007
1       357
Name: Class, dtype: int64

In [10]:
x.isnull().sum()

Time      0
Amount    0
dtype: int64

In [11]:
def create_model(model) :  #here create_model() user defined function name
    #model is a user defined parameter which hold the object of algorithm
    model.fit(x_train,y_train) #train the model with 70% training data
    y_pred=model.predict(x_test) #test the model with 30% input
    #print confusion matrix
    print(confusion_matrix(y_test,y_pred))
    #print classification report
    print(classification_report(y_test,y_pred))
    return model

In [12]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression 

In [13]:
lr=LogisticRegression()


In [14]:
lr=create_model(lr)

[[85308     0]
 [  135     0]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85308
           1       0.00      0.00      0.00       135

    accuracy                           1.00     85443
   macro avg       0.50      0.50      0.50     85443
weighted avg       1.00      1.00      1.00     85443



In [15]:
from imblearn.over_sampling import RandomOverSampler

In [16]:
ros=RandomOverSampler(random_state=1)

In [17]:
x_train1,y_train1=ros.fit_resample(x_train,y_train)

In [18]:
x_train1.shape,y_train1.shape

((398014, 2), (398014,))

In [19]:
x_test1,y_test1=ros.fit_resample(x_test,y_test)

In [20]:
y_test1.value_counts()

0    85308
1    85308
Name: Class, dtype: int64

In [21]:
def create_model(model) :  #here create_model() user defined function name
    #model is a user defined parameter which hold the object of algorithm
    model.fit(x_train1,y_train1) #train the model with 70% training data
    y_pred=model.predict(x_test1) #test the model with 30% input
    #print confusion matrix
    print(confusion_matrix(y_test1,y_pred))
    #print classification report
    print(classification_report(y_test1,y_pred))
    return model

In [22]:
lr=LogisticRegression()

In [23]:
lr=create_model(lr)

[[43584 41724]
 [37241 48067]]
              precision    recall  f1-score   support

           0       0.54      0.51      0.52     85308
           1       0.54      0.56      0.55     85308

    accuracy                           0.54    170616
   macro avg       0.54      0.54      0.54    170616
weighted avg       0.54      0.54      0.54    170616



In [24]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
dt=DecisionTreeClassifier(random_state=1)

In [26]:
dt=create_model(dt)

[[85191   117]
 [75277 10031]]
              precision    recall  f1-score   support

           0       0.53      1.00      0.69     85308
           1       0.99      0.12      0.21     85308

    accuracy                           0.56    170616
   macro avg       0.76      0.56      0.45    170616
weighted avg       0.76      0.56      0.45    170616



In [27]:
dict={'Input Columns':x.columns,'IG':dt.feature_importances_ }
#IG means information Gain
#convert dictionary into DataFrame
df1=pd.DataFrame(dict)
#sorting dataframe df1 according to IG column in descending order 
#use inbuilt method sort_values() of pandas library
df1.sort_values('IG',ascending=False) #by default ascending=True 
#means ascending order

Input Columns        IG
0          Time  0.501847
1        Amount  0.498153

In [28]:
dt1=DecisionTreeClassifier(random_state=1,max_depth=5) 
#method bydefault use gini index
#call function 
print("Confusion Matrix and Classification report")
dt1=create_model(dt1)

Confusion Matrix and Classification report
[[66758 18550]
 [37242 48066]]
              precision    recall  f1-score   support

           0       0.64      0.78      0.71     85308
           1       0.72      0.56      0.63     85308

    accuracy                           0.67    170616
   macro avg       0.68      0.67      0.67    170616
weighted avg       0.68      0.67      0.67    170616



In [29]:
dt1=DecisionTreeClassifier(random_state=1,max_depth=6,
                               criterion='entropy') 
#method bydefault use gini index
#call function 

print("Confusion Matrix and Classification report")
dt1=create_model(dt1)

Confusion Matrix and Classification report
[[68139 17169]
 [35892 49416]]
              precision    recall  f1-score   support

           0       0.65      0.80      0.72     85308
           1       0.74      0.58      0.65     85308

    accuracy                           0.69    170616
   macro avg       0.70      0.69      0.69    170616
weighted avg       0.70      0.69      0.69    170616



In [30]:
features=x.columns.tolist()
#to store all input columns in features user defined list object

plt.figure(figsize=(20,20))
#from sklearn import tree
#_=tree.plot_tree(dt1,feature_names=features,filled=True)

<Figure size 2000x2000 with 0 Axes>

<Figure size 2000x2000 with 0 Axes>

In [31]:
from sklearn.ensemble import RandomForestClassifier 

In [32]:
rfc=RandomForestClassifier(random_state=1,n_estimators=65)
#n_estimators inbuilt parameter of RandomForestClassifier  class
    #how many no. of decisiontree for train the model
#call function
rfc=create_model(rfc)    

[[85248    60]
 [75921  9387]]
              precision    recall  f1-score   support

           0       0.53      1.00      0.69     85308
           1       0.99      0.11      0.20     85308

    accuracy                           0.55    170616
   macro avg       0.76      0.55      0.44    170616
weighted avg       0.76      0.55      0.44    170616



In [33]:
rfc.feature_importances_

array([0.48573539, 0.51426461])

In [34]:
from sklearn.ensemble import AdaBoostClassifier

In [35]:
ada=AdaBoostClassifier(random_state=1,n_estimators=3)
    
#call function 
ada=create_model(ada)
ada.feature_importances_ #to show information gain of each features

[[65974 19334]
 [35405 49903]]
              precision    recall  f1-score   support

           0       0.65      0.77      0.71     85308
           1       0.72      0.58      0.65     85308

    accuracy                           0.68    170616
   macro avg       0.69      0.68      0.68    170616
weighted avg       0.69      0.68      0.68    170616



array([0.33333333, 0.66666667])

In [36]:
from sklearn.ensemble import GradientBoostingClassifier 
from sklearn.svm import LinearSVC
#create object 
svc=LinearSVC(random_state=1)#hard margin

In [37]:
gbc=GradientBoostingClassifier (random_state=1,n_estimators=72)
   
#call function
gbc=create_model(gbc)

[[71102 14206]
 [34721 50587]]
              precision    recall  f1-score   support

           0       0.67      0.83      0.74     85308
           1       0.78      0.59      0.67     85308

    accuracy                           0.71    170616
   macro avg       0.73      0.71      0.71    170616
weighted avg       0.73      0.71      0.71    170616



In [38]:
from sklearn.svm import LinearSVC
#create object 
svc=LinearSVC(random_state=1)#hard margin

In [39]:
svc=create_model(svc)

[[43580 41728]
 [37241 48067]]
              precision    recall  f1-score   support

           0       0.54      0.51      0.52     85308
           1       0.54      0.56      0.55     85308

    accuracy                           0.54    170616
   macro avg       0.54      0.54      0.54    170616
weighted avg       0.54      0.54      0.54    170616



In [40]:
svc1=LinearSVC(random_state=1,C=0.9)

In [41]:
svc1=create_model(svc1)

[[43536 41772]
 [37241 48067]]
              precision    recall  f1-score   support

           0       0.54      0.51      0.52     85308
           1       0.54      0.56      0.55     85308

    accuracy                           0.54    170616
   macro avg       0.54      0.54      0.54    170616
weighted avg       0.54      0.54      0.54    170616



In [42]:
from sklearn.svm import SVC

In [43]:
p_svc=SVC(random_state=1,kernel='poly')

In [ ]:
p_svc=create_model(p_svc)

In [ ]:
r_svc=SVC(random_state=1,kernel="rbf")
r_svc=create_model(r_svc)